spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
#     show-sql: true #System.out.-
      format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

#  thymeleaf:
#    prefix: classpath:src/main/resources/
#    check-template-location: true
#    suffix: .html
#    mode: HTML5
#    cache: false

logging:
  level:
    org.hibernate.SQL: debug  #log
    org.hibernate.type: trace
