spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#     show-sql: true #System.out.-
        format_sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        ## 아래 옵션 왠만하면 키는게 좋음
        default_batch_fetch_size: 100
#    open-in-view: false

#  thymeleaf:
#    prefix: classpath:src/main/resources/
#    check-template-location: true
#    suffix: .html
#    mode: HTML5
#    cache: false

logging:
  level:
    org.hibernate.SQL: debug  #log
    org.hibernate.type: trace
